name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions: read-all

jobs:
  hello_world_job:
    name: Hello job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello World Step
        run: echo "Hello, World!"

  goodbye_world_job:
    name: Goodbye job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Goodbye World Step
        run: echo "Goodbye, World!"
